#[derive(Debug, Clone, Copy, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AgentDefinition {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub display_name: &'static str,
    pub homepage: &'static str,
    pub binary_name: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub npm_package: Option<&'static str>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cargo_package: Option<&'static str>,
    #[serde(skip_serializing_if = "<[_]>::is_empty")]
    pub cargo_install_args: &'static [&'static str],
}

pub fn all_agents() -> &'static [AgentDefinition] {
    &AGENTS
}

pub fn resolve_agent(input: &str) -> Option<AgentDefinition> {
    AGENTS
        .iter()
        .copied()
        .find(|agent| agent.name == input || agent.aliases.contains(&input))
}

pub fn self_update_commands(agent: AgentDefinition) -> Vec<&'static str> {
    match agent.name {
        "amp" => vec!["amp update"],
        "auggie" => vec!["auggie upgrade"],
        "claude" => vec!["claude update", "claude upgrade"],
        "codebuddy" => vec!["codebuddy update"],
        "codex" => vec!["codex --upgrade"],
        "crush" => vec!["crush update"],
        "cursor" => vec!["agent update"],
        "deepseek" => vec!["deepseek update"],
        "devin" => vec!["devin update"],
        "droid" => vec!["droid update"],
        "forgecode" => vec!["forge update"],
        "goose" => vec!["goose update"],
        "kilo" => vec!["kilo upgrade"],
        "kimi" => vec!["uv tool upgrade kimi-cli --no-cache"],
        "opencode" => vec!["opencode upgrade"],
        "openhands" => vec!["uv tool upgrade openhands --python 3.12"],
        "pi" => vec!["pi update"],
        "qoder" => vec!["qodercli update"],
        "reasonix" => vec!["reasonix update"],
        "vtcode" => vec!["vtcode update"],
        _ => Vec::new(),
    }
}

const AGENTS: [AgentDefinition; 28] = [
    AgentDefinition {
        name: "auggie",
        aliases: &[],
        display_name: "Auggie CLI",
        homepage: "https://docs.augmentcode.com/cli/overview",
        binary_name: "auggie",
        npm_package: Some("@augmentcode/auggie"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "autohand",
        aliases: &["autohand-cli"],
        display_name: "Autohand Code CLI",
        homepage: "https://autohand.ai/cli/",
        binary_name: "autohand",
        npm_package: Some("autohand-cli"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "amp",
        aliases: &[],
        display_name: "Amp",
        homepage: "https://ampcode.com/",
        binary_name: "amp",
        npm_package: Some("@sourcegraph/amp"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "claude",
        aliases: &[],
        display_name: "Claude Code",
        homepage: "https://code.claude.com/docs",
        binary_name: "claude",
        npm_package: Some("@anthropic-ai/claude-code"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "codebuddy",
        aliases: &["codebuddy-code"],
        display_name: "CodeBuddy Code",
        homepage: "https://www.codebuddy.cn/docs/cli/installation",
        binary_name: "codebuddy",
        npm_package: Some("@tencent-ai/codebuddy-code"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "codex",
        aliases: &[],
        display_name: "Codex CLI",
        homepage: "https://developers.openai.com/codex/cli",
        binary_name: "codex",
        npm_package: Some("@openai/codex"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "copilot",
        aliases: &[],
        display_name: "GitHub Copilot CLI",
        homepage: "https://github.com/features/copilot/cli",
        binary_name: "copilot",
        npm_package: Some("@github/copilot"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "crush",
        aliases: &[],
        display_name: "Crush",
        homepage: "https://github.com/charmbracelet/crush",
        binary_name: "crush",
        npm_package: Some("@charmland/crush"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "cursor",
        aliases: &["agent"],
        display_name: "Cursor CLI",
        homepage: "https://cursor.com/docs/cli",
        binary_name: "agent",
        npm_package: None,
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "deepseek",
        aliases: &["deepseek-tui"],
        display_name: "DeepSeek TUI",
        homepage: "https://github.com/Hmbown/DeepSeek-TUI",
        binary_name: "deepseek",
        npm_package: Some("deepseek-tui"),
        cargo_package: Some("deepseek-tui-cli"),
        cargo_install_args: &["--locked"],
    },
    AgentDefinition {
        name: "devin",
        aliases: &[],
        display_name: "Devin for Terminal",
        homepage: "https://cli.devin.ai/",
        binary_name: "devin",
        npm_package: None,
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "droid",
        aliases: &[],
        display_name: "Droid",
        homepage: "https://docs.factory.ai/cli/getting-started/overview",
        binary_name: "droid",
        npm_package: Some("droid"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "forgecode",
        aliases: &["forge"],
        display_name: "ForgeCode",
        homepage: "https://forgecode.dev",
        binary_name: "forge",
        npm_package: Some("forgecode"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "gemini",
        aliases: &[],
        display_name: "Gemini CLI",
        homepage: "https://google-gemini.github.io/gemini-cli/docs/",
        binary_name: "gemini",
        npm_package: Some("@google/gemini-cli"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "goose",
        aliases: &[],
        display_name: "Goose",
        homepage: "https://github.com/aaif-goose/goose",
        binary_name: "goose",
        npm_package: None,
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "jcode",
        aliases: &[],
        display_name: "jcode CLI",
        homepage: "https://github.com/1jehuang/jcode",
        binary_name: "jcode",
        npm_package: None,
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "junie",
        aliases: &[],
        display_name: "Junie CLI",
        homepage: "https://junie.jetbrains.com/docs/junie-cli.html",
        binary_name: "junie",
        npm_package: Some("@jetbrains/junie"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "kilo",
        aliases: &[],
        display_name: "Kilo CLI",
        homepage: "https://kilo.ai/docs/cli",
        binary_name: "kilo",
        npm_package: Some("@kilocode/cli"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "kimi",
        aliases: &["kimi-code", "kimi-cli"],
        display_name: "Kimi Code",
        homepage: "https://moonshotai.github.io/kimi-cli/",
        binary_name: "kimi",
        npm_package: None,
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "kiro",
        aliases: &["kiro-cli"],
        display_name: "Kiro CLI",
        homepage: "https://kiro.dev/cli/",
        binary_name: "kiro-cli",
        npm_package: None,
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "openhands",
        aliases: &[],
        display_name: "OpenHands CLI",
        homepage: "https://docs.openhands.dev/openhands/usage/cli/installation",
        binary_name: "openhands",
        npm_package: None,
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "opencode",
        aliases: &[],
        display_name: "OpenCode",
        homepage: "https://opencode.ai",
        binary_name: "opencode",
        npm_package: Some("opencode-ai"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "pi",
        aliases: &[],
        display_name: "Pi",
        homepage: "https://pi.dev",
        binary_name: "pi",
        npm_package: Some("@mariozechner/pi-coding-agent"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "qoder",
        aliases: &["qodercli"],
        display_name: "Qoder CLI",
        homepage: "https://docs.qoder.com/cli/quick-start",
        binary_name: "qodercli",
        npm_package: Some("@qoder-ai/qodercli"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "qwen",
        aliases: &[],
        display_name: "Qwen Code",
        homepage: "https://qwenlm.github.io/qwen-code-docs/",
        binary_name: "qwen",
        npm_package: Some("@qwen-code/qwen-code"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "reasonix",
        aliases: &["deepseek-reasonix"],
        display_name: "Reasonix",
        homepage: "https://github.com/esengine/DeepSeek-Reasonix",
        binary_name: "reasonix",
        npm_package: Some("reasonix"),
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "vibe",
        aliases: &["mistral-vibe"],
        display_name: "Mistral Vibe",
        homepage: "https://docs.mistral.ai/mistral-vibe/terminal/install",
        binary_name: "vibe",
        npm_package: None,
        cargo_package: None,
        cargo_install_args: &[],
    },
    AgentDefinition {
        name: "vtcode",
        aliases: &[],
        display_name: "VTCode",
        homepage: "https://github.com/vinhnx/vtcode",
        binary_name: "vtcode",
        npm_package: None,
        cargo_package: Some("vtcode"),
        cargo_install_args: &[],
    },
];
